const peliculas =
    [
        { id: '1', title: 'THE AVENGERS', year: '2012', check: false, platforms: [] },
        { id: '2', title: 'AVATAR', year: '2009', check: false, platforms: [] },
        { id: '3', title: 'STAR WARS', year: '1977', check: false, platforms: [] },
        { id: '4', title: 'JURASSIC PARK', year: '1993', check: false, platforms: [] },
        { id: '5', title: 'DR. NO', year: '1962', check: false, platforms: [] },
        { id: '6', title: 'FAST AND FURIOUS', year: '2001', check: false, platforms: [] },
        { id: '7', title: 'HARRY POTTER', year: '2001', check: false, platforms: [] },
        { id: '8', title: 'IRON MAN', year: '2008', check: false, platforms: [] },
        { id: '9', title: 'CAPTAIN AMERICA', year: '2011', check: false, platforms: [] },
        { id: '10', title: 'THE SEARCHERS', year: '1956', check: false, platforms: [] },
        { id: '11', title: 'SPIDER MAN', year: '2002', check: false, platforms: [] },
        { id: '12', title: 'TRANSFORMERS', year: '2007', check: false, platforms: [] },
        { id: '13', title: '1408', year: '2007', check: false, platforms: [] },
        { id: '14', title: 'PIRATES OF THE CARIBBEAN', year: '2003', check: false, platforms: [] },
        { id: '15', title: 'ANACONDA', year: '1997', check: false, platforms: [] },
        { id: '16', title: 'SUPERMAN', year: '1978', check: false, platforms: [] },
        { id: '17', title: 'INDIANA JONES', year: '1981', check: false, platforms: [] },
        { id: '18', title: 'LARA CROFT: TOMB RAIDER', year: '2001', check: false, platforms: [] },
        { id: '19', title: 'NATIONAL TREASURE ', year: '2004', check: false, platforms: [] },
        { id: '20', title: 'THE TERMINATOR', year: '1984', check: false, platforms: [] },
        { id: '21', title: 'THE DA VINCI CODE', year: '2006', check: false, platforms: [] },
        { id: '22', title: 'THE MATRIX', year: '1999', check: false, platforms: [] },
        { id: '23', title: 'PREDATOR', year: '1987', check: false, platforms: [] },
        { id: '24', title: 'JAWS', year: '1975', check: false, platforms: [] },
        { id: '25', title: 'THE HUNGER GAMES', year: '2012', check: false, platforms: [] },
        { id: '26', title: 'LIMITLESS', year: '2011', check: false, platforms: [] },
        { id: '27', title: 'AROUND THE WORLD IN 80 DAYS', year: '2004', check: false, platforms: [] },
        { id: '28', title: 'ARMAGEDDON', year: '1998', check: false, platforms: [] },
        { id: '29', title: 'FORREST GUMP', year: '1994', check: false, platforms: [] },
        { id: '30', title: 'THE SILENCE OF THE LAMBS', year: '1991', check: false, platforms: [] },
        { id: '31', title: 'IT', year: '2017', check: false, platforms: [] },
        { id: '32', title: 'THE BUTTERFLY EFFECT', year: '2004', check: false, platforms: [] },
        { id: '33', title: 'THE RING', year: '2002', check: false, platforms: [] },
        { id: '34', title: 'KING KONG', year: '1933', check: false, platforms: [] },
        { id: '35', title: 'BONNIE AND CLYDE', year: '1967', check: false, platforms: [] },
        { id: '36', title: 'SAW', year: '2003', check: false, platforms: [] },
        { id: '37', title: 'THE NUMBER 23', year: '2007', check: false, platforms: [] },
        { id: '38', title: 'RESIDENT EVIL', year: '2002', check: false, platforms: [] },
        { id: '39', title: 'SHERLOCK HOLMES', year: '2009', check: false, platforms: [] },
        { id: '40', title: 'THE FIFTH ELEMENT', year: '1997', check: false, platforms: [] },
        { id: '41', title: 'LEON', year: '1994', check: false, platforms: [] },
        { id: '42', title: 'SCREAM', year: '1996', check: false, platforms: [] },
        { id: '43', title: 'INCEPTION', year: '2010', check: false, platforms: [] },
        { id: '44', title: 'SOME LIKE IT HOT', year: '1959', check: false, platforms: [] },
        { id: '45', title: 'THE LORD OF THE RINGS', year: '2001', check: false, platforms: [] },
        { id: '46', title: 'TWILIGHT', year: '2008', check: false, platforms: [] },
        { id: '47', title: 'RAMBO FIRST BLOOD', year: '1985', check: false, platforms: [] },
        { id: '48', title: 'ALIEN', year: '1979', check: false, platforms: [] },
        { id: '49', title: 'BAD BOYS', year: '1995', check: false, platforms: [] },
        { id: '50', title: 'HACHI A DOG\'S TALE', year: '2009', check: false, platforms: [] },
        { id: '51', title: 'THE GODFATHER', year: '1972', check: false, platforms: [] },
        { id: '52', title: 'HOME ALONE', year: '1990', check: false, platforms: [] },
        { id: '53', title: 'X-MEN', year: '2000', check: false, platforms: [] },
        { id: '54', title: 'THE ILLUSIONIST', year: '2006', check: false, platforms: [] },
        { id: '55', title: 'THE MAZE RUNNER', year: '2014', check: false, platforms: [] },
        { id: '56', title: 'GODZILLA', year: '1998', check: false, platforms: [] },
        { id: '57', title: 'PLATOON', year: '1986', check: false, platforms: [] },
        { id: '58', title: 'THE SIXTH SENSE', year: '1999', check: false, platforms: [] },
        { id: '59', title: 'PULP FICTION', year: '1994', check: false, platforms: [] },
        { id: '60', title: 'CRANK', year: '2006', check: false, platforms: [] },
        { id: '61', title: 'OCEANS ELEVEN ', year: '2001', check: false, platforms: [] },
        { id: '62', title: 'THE WHOLE NINE YARDS', year: '2000', check: false, platforms: [] },
        { id: '63', title: 'ROCKY', year: '1976', check: false, platforms: [] },
        { id: '64', title: 'SECRET WINDOW', year: '2004', check: false, platforms: [] },
        { id: '65', title: 'TAXI DRIVER', year: '1976', check: false, platforms: [] },
        { id: '66', title: 'SPARTACUS', year: '1960', check: false, platforms: [] },
        { id: '67', title: 'THE EXPENDABLES', year: '2010', check: false, platforms: [] },
        { id: '68', title: 'G.I. JANE', year: '1997', check: false, platforms: [] },
        { id: '69', title: 'THE MIST', year: '2007', check: false, platforms: [] },
        { id: '70', title: 'BOHEMIAN RHAPSODY', year: '2018', check: false, platforms: [] },
        { id: '71', title: 'LAW ABIDING CITIZEN', year: '2009', check: false, platforms: [] },
        { id: '72', title: 'THE GREEN MILE', year: '1999', check: false, platforms: [] },
        { id: '73', title: 'FANTASTIC BEASTS AND WHERE TO FIND THEM', year: '2016', check: false, platforms: [] },
        { id: '74', title: 'PSYCHO', year: '1960', check: false, platforms: [] },
        { id: '75', title: 'THE DARK KNIGHT', year: '2008', check: false, platforms: [] },
        { id: '76', title: 'CASABLANCA', year: '1942', check: false, platforms: [] },
        { id: '77', title: 'KILL BILL', year: '2003', check: false, platforms: [] },
        { id: '78', title: 'GOODFELLAS', year: '1990', check: false, platforms: [] },
        { id: '79', title: 'VERTIGO', year: '1958', check: false, platforms: [] },
        { id: '80', title: 'CITY LIGHTS', year: '1931', check: false, platforms: [] },
        { id: '81', title: 'BLADE RUNNER', year: '1982', check: false, platforms: [] },
        { id: '82', title: 'MISSION: IMPOSSIBLE', year: '1996', check: false, platforms: [] },
        { id: '83', title: 'ET. THE EXTRA-TERRESTRIAL', year: '1982', check: false, platforms: [] },
        { id: '84', title: 'LE TRANSPORTEUR', year: '2002', check: false, platforms: [] },
        { id: '85', title: 'VALKYRIE', year: '2008', check: false, platforms: [] },
        { id: '86', title: 'SAVING PRIVATE RYAN', year: '1998', check: false, platforms: [] },
        { id: '87', title: 'SCHINDLER\'S LIST', year: '1993', check: false, platforms: [] },
        { id: '88', title: 'SHAWSHANK REDEMPTION', year: '1994', check: false, platforms: [] },
        { id: '89', title: 'THE WIZARD OF OZ', year: '1939', check: false, platforms: [] },
        { id: '90', title: 'BACK TO THE FUTURE', year: '1985', check: false, platforms: [] },
        { id: '91', title: 'CITIZEN KANE', year: '1941', check: false, platforms: [] },
        { id: '92', title: 'GONE WITH THE WIND', year: '1939', check: false, platforms: [] },
        { id: '93', title: 'INDEPENDENCE DAY', year: '1996', check: false, platforms: [] },
        { id: '94', title: 'TITANIC', year: '1997', check: false, platforms: [] },
        { id: '95', title: 'ONE FLEW OVER THE CUCKOO\'S NEST', year: '1975', check: false, platforms: [] },
        { id: '96', title: 'THE SHINING', year: '1980', check: false, platforms: [] },
        { id: '97', title: 'THE WOLF OF WALL STREET', year: '2013', check: false, platforms: [] },
        { id: '98', title: 'THE BIRTH OF A NATION', year: '2016', check: false, platforms: [] },
        { id: '99', title: 'TAXI', year: '1988', check: false, platforms: [] },
        { id: '100', title: 'PET SEMATARY', year: '2019', check: false, platforms: [] },
    ]

export default peliculas